### ISSUE TITLE
Facing issue with StompNet library

### ISSUE THREAD

**Issue by Vanita-Agarwal** [krlito/StompNet#1]
We have a Websocket Stomp server built in Java (Spring based) hosted in localhost with 8080 port
We are facing an connectivity issue while using Stompclient library and getting following error - 

Error list-
• Message = "This protocol version is not supported."
• DualMode = 'tcpClient.Client.DualMode' threw an exception of type 'System.NotSupportedException'
• tcpClient.Client.EnableBroadcast' threw an exception of type 'System.Net.Sockets.SocketException'

• An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call

• base = {"This stream does not support seek operations."}

• HTTP/1.1 400 Bad Request' is not a valid STOMP server command.  

Can anyone please suggest if you have successfully created / used any C# client library with a spring based STOMP over Web Socket server.

Please let us know if you need more details.
Appreciate your quick response..

Thanks
Vanita

**Comment by krlito** [comment]
The library does not work with WebSockets out of the box. Related to #3 .
