### ISSUE TITLE
Is there a way we can run the the stompclient over http /websocket?

### ISSUE THREAD

**Issue by jliu1970** [krlito/StompNet#3]
Rather than a TCP connection, is there a way we can connect through a websocket connection?
Thanks
Jimmy

**Comment by krlito** [comment]
Sorry for the late answer.

The library was not really thought to be used with WebSockets but with Streams of bytes.

I suppose an adaptor from the WebSocket interface to Stream could be built. If you wanted to parse a single message, you can write it into a MemoryStream. Then, pass the MemoryStream to Stomp12FrameReader. [For example, this test.](https://github.com/krlito/StompNet/blob/64c12cac177de83ed83cfc58fa78c8d037c2808d/StompNet.Tests/Stomp12FrameReaderTest.cs#L73-L81)
