### ISSUE TITLE
Incorrect behaviour in SerialTaskExecutor then queued task is faulted

### ISSUE THREAD

**Issue by Eykhler** [krlito/StompNet#4]
I faced with a problem, that when the exception is thrown in WriteAsync method of the IStompFrameWriter instance then the TaskCancellationSource returned by SerialTaskExecutor has always state of successfull completion of the queued task. By analyzing and debugging the extension method TrySet of the class TaskCompletionSourceExtensions I'm found what the faulted awaited task, has also flag IsCompleted, so your code is never set exception in the TaskCancellationSource.

So the correct code is:
```C#
/// <summary>
/// TaskCompletionSource extensions.
/// </summary>
internal static class TaskCompletionSourceExtensions
{
	public static void TrySet<T>(this TaskCompletionSource<T> tcs, Task task) where T : class 
	{
		if (task.IsFaulted)
		{
			tcs.TrySetException(task.Exception.InnerExceptions);
		}
		else if (task.IsCanceled)
		{
			tcs.TrySetCanceled();
		}
		else
		{
			Task<T> taskWithResult = task as Task<T>;
			tcs.TrySetResult(taskWithResult == null ? null : taskWithResult.Result);
		}
	}
}

**Comment by krlito** [comment]
Code is updated. Thanks.
