### ISSUE TITLE
.net standard 2

### ISSUE THREAD

**Issue by schmitz85** [krlito/StompNet#5]
Hi, your lib works like a charm and the pull request from @sbou too, plz accept the heartbeat, and publish a .net standard 2 on nuget, to run it in .net standard you don't need to change any line, your code is full compatible with it.

**Comment by krlito** [comment]
Thanks for your input.
The package now supports .NET Standard 1.5. Regarding heartbeat, I am still not sure the proposed implementation is the right fit, but I hope I can bring a solution to this requirement soon.
